// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validator.proto

package com.training.java.grpc.validator.artifacts.entity;

public interface ValidationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:validator.Validation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string postal_code = 1;</code>
   */
  String getPostalCode();
  /**
   * <code>string postal_code = 1;</code>
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <code>string province = 2;</code>
   */
  String getProvince();
  /**
   * <code>string province = 2;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();
}
