// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validator.proto

package com.training.java.grpc.validator.artifacts.entity;

public interface ValidationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:validator.ValidationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   */
  int getResult();

  /**
   * <code>string propuesta = 2;</code>
   */
  String getPropuesta();
  /**
   * <code>string propuesta = 2;</code>
   */
  com.google.protobuf.ByteString
      getPropuestaBytes();
}
