// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validator.proto

package com.training.java.grpc.validator.artifacts.entity;

public interface ValidationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:validator.ValidationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.validator.Validation request = 1;</code>
   */
  boolean hasRequest();
  /**
   * <code>.validator.Validation request = 1;</code>
   */
  Validation getRequest();
  /**
   * <code>.validator.Validation request = 1;</code>
   */
  ValidationOrBuilder getRequestOrBuilder();
}
