// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validator.proto

package com.training.java.grpc.validator.artifacts.entity;

public final class Validator {
  private Validator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validator_Validation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validator_Validation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validator_ValidationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validator_ValidationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validator_ValidationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validator_ValidationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017validator.proto\022\tvalidator\"3\n\nValidati" +
      "on\022\023\n\013postal_code\030\001 \001(\t\022\020\n\010province\030\002 \001(" +
      "\t\";\n\021ValidationRequest\022&\n\007request\030\001 \001(\0132" +
      "\025.validator.Validation\"7\n\022ValidationResp" +
      "onse\022\016\n\006result\030\001 \001(\005\022\021\n\tpropuesta\030\002 \001(\t2" +
      "\\\n\021ValidationService\022G\n\010Validate\022\034.valid" +
      "ator.ValidationRequest\032\035.validator.Valid" +
      "ationResponseB\027\n\023com.proto.validatorP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_validator_Validation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_validator_Validation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validator_Validation_descriptor,
        new String[] { "PostalCode", "Province", });
    internal_static_validator_ValidationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_validator_ValidationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validator_ValidationRequest_descriptor,
        new String[] { "Request", });
    internal_static_validator_ValidationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_validator_ValidationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validator_ValidationResponse_descriptor,
        new String[] { "Result", "Propuesta", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
